# Dependencies
markdown:         kramdown
#highlighter:      pygments.rb

# Permalinks
permalink:        pretty
#relative_permalinks: true
gem: [jekyll-paginate, jekyll-gists,gist,jekyll-sitemap,jekyll-seo-tag]

# Setup
title:            Prasad Ostwal
tagline:          'Prasad Ostwal blog'
description:      'My personal blog of tech and life'
url:              http://ostwalprasad.github.io
baseurl:          /
imageurl: /


author:
  name:           'Prasad Ostwal'
  url:            https://twitter.com/ostwalprasad

paginate:         5

github_username: ostwalprasad
linkedin_username: ostwalprasad
twitter_username: ostwalprasad
email: prasadostwal@gmail.com
# Custom vars
version:          1.0.3

disqus:
    shortname: "ostwalprasad-github-io"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  


github:
  repo:           https://github.com/ostwalprasad
